MyBestProject/config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resource :profile
    resources :devices, shallow: true

    get :search, on: :collection
    get :preview, on: :member
    patch :change_balance, on: :member
  end

  namespace :admin do
    root 'home#main'
  end

  namespace :api do
    namespace :v1 do
      resources :users
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  # authenticated :user, lambda { |u| u.has_role? :admin } do
  # end

  root 'home#main'
end

MyBestProject/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MyBestProject/app/models/device.rb
# == Schema Information
#
# Table name: devices
#
#  id            :bigint           not null, primary key
#  address       :string
#  vendor        :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  user_id       :bigint
#  device_status :integer
#
class Device < ApplicationRecord
  belongs_to :user, optional: true, counter_cache: true
  scope :tp_links, -> { where(vendor: 'TP-Link') }

  # validates :address, uniqueness: true
  validates :address, uniqueness: { scope: :user }

  enum device_status: { online: 0, offline: 1, loading: 2 }
end

MyBestProject/app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id          :bigint           not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Group < ApplicationRecord
  # has_and_belongs_to_many :users
  has_many :groups_users
  has_many :users, through: :groups_users
end

MyBestProject/app/models/groups_user.rb
# == Schema Information
#
# Table name: groups_users
#
#  user_id  :bigint           not null
#  group_id :bigint           not null
#
class GroupsUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

MyBestProject/app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id           :bigint           not null, primary key
#  phone_number :string
#  user_id      :bigint
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  address      :string
#
class Profile < ApplicationRecord
  belongs_to :user
  belongs_to :human, foreign_key: 'user_id', class_name: 'User', optional: true
  # delegate :city, to: :location
end

MyBestProject/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :bigint           not null, primary key
#  first_name :string
#  last_name  :string
#  email      :string
#  age        :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  status     :integer          default("normal")
#
class User < ApplicationRecord
  ADULT_AGE = 18
  before_create :set_age
  after_create :send_email

  default_scope -> { order(id: :desc) }
  scope :adults, ->(age_param) { where('age >= ?', age_param).order(age: :desc) }

  has_one :profile, dependent: :destroy
  has_one :expert, class_name: 'Profile'
  has_many :devices, dependent: :nullify
  # has_and_belongs_to_many :groups
  has_many :groups_users
  has_many :groups, through: :groups_users

  validates :email, presence: true, uniqueness: true

  enum status: { normal: 0, premium: 1, gold: 2 }
  accepts_nested_attributes_for :profile
  accepts_nested_attributes_for :devices, allow_destroy: true

  delegate :phone_number, to: :profile, allow_nil: true #, prefix: true
  # delegate :city, to: :profile, allow_nil: true

  private

  def set_age
    self.age = (16..60).to_a.sample
  end

  def send_email
    UserMailer.with(user_id: id).welcome_user.deliver_later
  end
end

MyBestProject/app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController

end

MyBestProject/app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::API

end

MyBestProject/app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < BaseController
      def index
        render json: AdminSerializer.new(User.all, { include: %i[profile] }).serializable_hash
      end

      def show
        render json: AdminSerializer.new(User.find(params[:id]), { include: %i[profile] }).serializable_hash
      end

      def create
        User.create(user_params)
      end

      private

      def user_params
        params.from_jsonapi.require(:user).permit(:first_name, :last_name, :email)
      end
    end
  end
end

MyBestProject/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActionController::ParameterMissing do |exception|
    render plain: exception.message, status: :unprocessable_entity
  end
end

MyBestProject/app/controllers/home_controller.rb
class HomeController < ApplicationController
end

MyBestProject/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @profile = Profile.find_by(user_id: params[:user_id])
  end
end

MyBestProject/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy change_balance]
  layout false, only: %i[new edit]

  def index
    @users = User.all.includes(:profile)
    @users = @users.where('age > ?', params[:age]) if params[:age]
    @users = @users.where('first_name LIKE ?', "%#{params[:name]}%") if params[:name]
    # @users = @users.where(User.arel_table[:first_name].matches(params[:name])) if params[:name]

    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end

  def create
    @user = User.create(user_params)

    respond_to do |format|
      format.js
      format.html do
        if @user.errors
          render json: @user.errors
        else
          redirect_to action: :index
        end
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.js do
          response.set_header('Content-Type', 'text/plain')
          render partial: 'table_row', locals: { user: @user }
        end

        format.html do
          flash[:notice] = 'User was updated'
          redirect_to action: :show
        end
      else
        flash[:alert] = @user.errors.full_messages
        redirect_to action: :edit
      end
    end
  end

  def new
    @user = User.new(profile: Profile.new)
    # 2.times { @user.devices.build }
  end

  def destroy
    if @user.destroy
      redirect_to users_path
    end
  end

  def search; end

  def preview; end

  def change_balance
    puts @user.balance
    puts '============'
    # @user.with_lock do
    @user.balance -= params[:credit].to_i
    @user.save
    # end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :age, :status, profile_attributes: %i[id address phone_number],
      devices_attributes: {})
  end

  def set_user
    @user = User.find params[:id]
  end
end

MyBestProject/app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

MyBestProject/app/helpers/application_helper.rb
module ApplicationHelper
end

MyBestProject/app/views/admin/home/main.html.erb
<h1>Welcome to Restricted Area, Admin!</h1>

MyBestProject/app/views/home/main.html.erb
<h1>Welcome to our website!</h1>

<%= link_to 'Users List', users_path %>

MyBestProject/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBestProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :head %>
  </head>

  <body>
    <br/>
    <br/>
    <%= flash[:notice] %>
    <header>
      <h1> I'm HEADER!</h1>
      <%= yield :header_email %>
    </header>

    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

MyBestProject/app/views/profiles/show.html.erb
<h1>Profiles#show</h1>

<h2><%= @profile.address %></h2>
<h2><%= @profile.phone_number %></h2>

MyBestProject/app/views/shared/_errors.html.slim
.alert.alert-danger
  ul
    - errors.each do |error|
      li = error

MyBestProject/app/views/users/_form.html.slim
.row
  .col-md-6.offset-md-3
    .errors
    = form_with model: @user, local: false, data: { id: @user.id } do |form|
      .mb-3
        = form.label :first_name, 'Your First Name', class: 'form-label'
        = form.text_field :first_name, class: 'form-control'

      .mb-3
        = form.label :last_name, class: 'form-label'
        = form.text_field :last_name, class: 'form-control'

      .mb-3
        = form.label :email, class: 'form-label'
        = form.email_field :email, class: 'form-control'

      .mb-3
        = form.label :age, class: 'form-label'
        = form.number_field :age, class: 'form-control'

      .mb-3
        = form.label :status, class: 'form-label'
        = form.select :status, User.statuses.keys, {}, class: 'form-select'

      .mb-3
        = form.fields_for :profile do |profile_form|
          .row
            .col-md-6
              = profile_form.text_field :address, placeholder: 'Enter Your Address', class: 'form-control'
            .col-md-6
              = profile_form.telephone_field :phone_number, placeholder: 'Enter Your Phone', class: 'form-control'

      .mb-3
        = form.fields_for :devices do |devices_form|
          .row.mb-3
            .col-md-4
              = devices_form.text_field :address, placeholder: 'IP Address', class: 'form-control'
            .col-md-4
              = devices_form.text_field :vendor, placeholder: 'Vendor', class: 'form-control'
            .col-md-4
              = devices_form.check_box :_destroy, class: 'form-check-input'

      .mt-3
        = form.submit class: 'btn btn-primary'

MyBestProject/app/views/users/_table_row.html.slim
tr id="row-#{user.id}"
  td = user.id
  td = user.first_name
  td = user.last_name
  td = user.email
  td = user.age
  td = user.phone_number
  td = user.devices_count
  td = user.created_at.strftime('%B %d, %Y %H:%M')
  td = user.updated_at.strftime('%B %d, %Y %H:%M')
  td
    = link_to 'View', user_path(user)
    | &nbsp;
    = link_to 'Edit', edit_user_path(user), class: 'modal-toggle'
    | &nbsp;
    = link_to 'Delete', user_path(user), method: :delete, remote: true, data: { confirm: 'Are you sure?' }

MyBestProject/app/views/users/_user.html.slim
h3 User #{user.id}
ul
  li = user.first_name
  li = user.last_name
  li = user.email

MyBestProject/app/views/users/_user_modal.html.slim
#user-modal.modal.fade
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        button.btn-close (type="button" class="" data-bs-dismiss="modal" aria-label="Close")
      .modal-body

MyBestProject/app/views/users/create.js.erb
<% if @user.errors.any? %>
  $('.errors').html("<%= j render 'shared/errors', errors: @user.errors.full_messages %>")
<% else %>
  window.location = '<%= users_path %>'
<% end %>

MyBestProject/app/views/users/edit.html.slim
h1 Edit User ID##{@user.id}

= render 'form'

MyBestProject/app/views/users/index.html.erb
<h1>Users#index</h1>

<table class='table'>
  <tr>
    <th>ID</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Age</th>
    <th>Phone</th>
    <th>Devices Count</th>
    <th>Created At</th>
    <th>Updated At</th>
    <th>Links</th>
  </tr>

  <% @users.each do |user| %>
    <%# <%= render partial: 'table_row', locals: { user: user } %>
    <%= render 'table_row', user: user %>
  <% end %>
</table>

<br/>

<%= link_to 'Create User', new_user_path, class: 'btn btn-primary modal-toggle'  %>

<%= render 'user_modal' %>
<%# <%= render @users %>

MyBestProject/app/views/users/new.html.slim
h1.text-center Create New User

= render 'form'

MyBestProject/app/views/users/show.html.erb
<h1>Users#show</h1>

<h2><%= @user.first_name %> <%= @user.last_name %></h2>
<%= link_to 'View Profile', user_profile_path(@user) %>

<% content_for :header_email do %>
  <h2>
    <%= @user.email %>
  </h2>
<% end %>